# Generated by Django 4.0.2 on 2022-03-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_owner_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_goal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('projects', 'Projects'), ('pledges', 'Pledges')], max_length=20),
        ),
    ]
