# Generated by Django 4.0.2 on 2022-03-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_badge_badge_goal_alter_badge_badge_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('badge_type', 'badge_goal')},
        ),
    ]
