# Generated by Django 4.0.2 on 2022-03-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
