# Generated by Django 4.0.2 on 2022-03-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_goal',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
    ]
