# Generated by Django 4.0.2 on 2022-04-20 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closing_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 11, 41, 35, 593399, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
